# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LasUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=4)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('totalChampionKills', models.IntegerField()),
                ('totalTurretsKilled', models.IntegerField()),
                ('totalMinionKills', models.IntegerField()),
                ('totalNeutralMinionsKilled', models.IntegerField()),
                ('totalAssists', models.IntegerField()),
                ('registrationDate', models.DateTimeField(verbose_name=b'registration date')),
            ],
        ),
    ]
