# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasuser',
            name='losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='region',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='registrationDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'registration date'),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='totalAssists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='totalChampionKills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='totalMinionKills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='totalNeutralMinionsKilled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='totalTurretsKilled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lasuser',
            name='wins',
            field=models.IntegerField(null=True),
        ),
    ]
