# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='player_id',
            new_name='playerId',
        ),
        migrations.AddField(
            model_name='user',
            name='registrationDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 23, 21, 44, 5, 153739, tzinfo=utc), verbose_name='registration date'),
            preserve_default=False,
        ),
    ]
